version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: Check shell scripts
          command: |
            shellcheck *.sh
